# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'

env:
 GitHubMail: "error@notavailable.live"
 GitHubName: "techierror"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    	- name: Running Ultroid
          run: |
            git config --global user.name ${GitHubName}
            git config --global user.email ${GitHubMail}
            git config --global credential.helper store
            git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.CREDS }} ultroid
            wget https://raw.githubusercontent.com/TeamUltroid/Ultroid/dev/Dockerfile
            sudo cp -r ./ultroid/. .

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t ultroid
